/**
    * @file    co2_sensor_controller.h
    * @brief   Function declarations for the CO2 sensor controller.
    * @details This file contains the interface for managing interactions with the MH-Z19B CO2 sensor.
    *          It includes initialization, measurement retrieval, and error handling functions.
    */

#ifndef CO2_SENSOR_CONTROLLER_H
#define CO2_SENSOR_CONTROLLER_H

namespace Co2SensorController {
    /**
     * @enum    SensorErrorCode
     * @brief   Error codes generated by the CO2 sensor controller.
     */
    enum SensorErrorCode : int {
        MEASUREMENT_NOT_VALID_ERROR = -1 ///< Measurement is outside the valid range
    };

    /**
     * @brief   Initializes the CO2 sensor module.
     * @details Sets up the MH-Z19B sensor by configuring pins, and preheating it.
     */
    void initialize();

    /**
     * @brief   Retrieves the current CO2 measurement in ppm.
     * @details Fetches the CO2 value using the MH-Z19B sensor and ensures it's within a valid range.
     * @return  The measured CO2 value in parts per million (ppm) if successful,
     *          or a SensorErrorCode indicating failure.
     */
    int get_measurement_in_ppm();
}

#endif // CO2_SENSOR_CONTROLLER_H
